### PR TITLE
Translations Update

### PR DESCRIPTION
**Pull request by abtheo**
Major Changes:
* Add Language Picker to NFT page
* Changes the header responsively on Mobile, now has two views:

512 to 398px header:
image

>398px header:
image

Minor Changes:
* Added Tagalog
* Update missing translations

### CODE REVIEW

**Comment by abtheo** [comment]
Oh yeah, also fixes the view on large phone screens. That's why I started coding 8 hours ago...
image

**Comment by abtheo** [comment]
Actually, maybe hold off on merging this for now. We need to add the new `BondPurchaseDialog` to translations also.

**Comment by Appppo** [comment]
The header layout in mobile view is broken.
I will do some UI tweaks later

**Comment by abtheo** [comment]
Alright that's all the translation fixes for now, but I'm sure they'll keep cropping up in weird places.

@Appppo I would definitely appreciate you taking a look at the styling, doing my best but this task is huge 😅❤

**Comment by Appppo** [comment]
@abtheo 
Language button in light mode:
https://www.figma.com/file/GOojXCnlNhX9cUCbnSZLA4/OtterClam-Internal?node-id=192%3A1365
image
Language button in dark mode:
https://www.figma.com/file/GOojXCnlNhX9cUCbnSZLA4/OtterClam-Internal?node-id=213%3A3520
image

The dropdown expanded style looks good now. No need to change that.

Icon asset:
https://www.figma.com/file/GOojXCnlNhX9cUCbnSZLA4/OtterClam-Internal?node-id=69%3A277
Please directly download the icon in svg file format and change the color by using CSS, thank you so much!

**Comment by Appppo** [comment]
And for language abbreviation displaying on the button in desktop view, please refer to [ISO 639-1](http://www.mathguide.de/info/tools/languagecode.html) or similar format. Thanks!

**Comment by abtheo** [comment]
Sure thing, I'm on it.

@Appppo I don't have permission to view the Icon File, could you please grant me access?

**Comment by Appppo** [comment]
@abtheo Sorry I gave the wrong link :(
Invitation sent.
Here you can see how the language button display on Light mode/Dark mode and XL/XS viewport:
https://www.figma.com/file/unTAWJfR6cHy6oxXwTqmMQ/OtterClam-Public?node-id=31%3A6932

Here's the language icon asset:
https://www.figma.com/file/unTAWJfR6cHy6oxXwTqmMQ/OtterClam-Public?node-id=31%3A6575

**Comment by abtheo** [comment]
https://user-images.githubusercontent.com/24249418/145915667-c45dc186-72ba-407c-90de-a032d6e50a68.mp4

**Comment by abtheo** [comment]
Ready for Review! ❤

**Review by otterclamking — COMMENTED** [review]
This is cool! but the shadow and layout is not aligned with design

Design
image

Brave Preview
image

**Comment by abtheo** [comment]
@otterclamking how's this?

image

**Comment by otterclamking** [comment]
There is still some missing style 😅 Let me merge this first. We can fix those later.

**Pull request merged**
