### PR TITLE
Treasury revenue

### PR DESCRIPTION
**Pull request by abtheo**
Big update for the Treasury Dashboard, showing info about revenue, buybacks, burns and more!

image
image

### CODE REVIEW

**Comment by abtheo** [comment]
Oh damn I forgot the Translations 😅
If anyone could please add the following to the Chinese local it'd be much appreciated:

```
buybacks: 'Buybacks',
burned: 'Burned',
clamToday: 'CLAM Distributed Today',
treasuryRevenue:
          'Daily income harvested from treasury investments. This does not reflect changes in the market value of treasury assets, only new liquid tokens entering the treasury.',
circulatingSupply:
          'The current number of CLAM tokens in circulation. The difference between the total and circulating supply is the amount of CLAM held by the DAO wallet.',
marketCap: 'Number of circulating CLAM multiplied by market price.',
        burned: 'Amount of CLAM permanently burned and removed from the supply.',
clamToday:
          'Total amount of CLAM which has been distributed today. This is divided proportionally between all stakers and Pearl Chest holders.',
backing: 'Market Value of Treasury Assets divided by the circulating supply of CLAM.',
```

**Comment by 0xthk** [comment]
> Oh damn I forgot the Translations 😅 If anyone could please add the following to the Chinese local it'd be much appreciated:
> The current number of CLAM tokens in circulation. The difference between the total and circulating supply is the amount of CLAM held by the DAO wallet.'

Suggest update: 'The current number of CLAM tokens in circulation. The difference between the total and circulating supply is the amount of CLAM held by the DAO wallet and Ottopia reward pool.

Here is the translation @abtheo 
```
buybacks: '回購',
burned: '燒毀',
clamToday: 'CLAM 今天分發',
treasuryRevenue: '每日國庫的投資收入，這不反應國庫的總淨資產價值變化，只顯示新增的收入部分。',
circulatingSupply: '流通中的 CLAM ，差額主要為 DAO 錢包和 Ottopia 獎勵池。',
marketCap: '流通的 CLAM 乘以市價',
burned: '由國庫回購並且燒毀的 CLAM 數量。',
clamToday: '今天總共分配的 CLAM 數量，按照質押與鎖倉的比例分配給質押者與珍珠寶盒的持有者。',
backing: '國庫淨資產總值除以流通的 CLAM 數量。',
```

**Comment by abtheo** [comment]
@0xthk thank you, I have added the translations and your suggestion

**Comment by abtheo** [comment]
> Think we should group stat number together. The layout is a little bit mess 😅

Sorry 😂

The problem I'm having is that I'd like to include 9 stats now instead of 6, which makes the dashboard page look like this:
image

which is even worse in my opinion, as it basically knocks the graphs all the way off the page 😅

Could @otterclamking or @Appppo suggest design changes to make this work? Or are you sure we should go for all 9 stats at the top? Happy to implement once I know what we're aiming for!

**Comment by abtheo** [comment]
>Think we should group stat number together. The layout is a little bit mess 😅

Ohh I see the issue with the bottom row now, thank you! ♥

image

**Comment by Appppo** [comment]
@abtheo Hi, the new dashboard that you've made is so clear and informative!

Here are some small UI tweaks I found and I will list them here. You can adjust the UI if you have time :D

**Comment by Appppo** [comment]
Figma file: 
https://www.figma.com/file/GOojXCnlNhX9cUCbnSZLA4/OtterClam-Internal?node-id=209%3A1439
(The mobile mockup is placed right beside the Desktop mockup)

Here are the listed UI tweaks:
1. The order of the section cards have changed a bit.
2. The padding of each card on desktop and mobile are different. You can find the actual pixel on the Figma mockups.
3. The text-only card layout in mobile versions is supposed to be 2 columns. Now it's only 1 column.
4. The tab button of "CLAM/USD" UI was refined
5. In both "Burned CLAM" and "CLAM Distributed Today", the unit changes when I switch the currency to "CLAM/USD". But since the currency button is placed in
App - Dashboard - XS - Light mode
App - Dashboard - XL - Light mode
 another graph section, it might be a little weird to change the currency accordingly in the user experience. I recommend that we show the CLAM (USD) directly on the card instead of switching it through the currency button.

**Comment by abtheo** [comment]
@Appppo thanks for the feedback, I have implemented the proposed changes. Ready for another review!

**Comment by Appppo** [comment]
@abtheo I've seen the preview app. It looks much better now! 😍

There are some of the tweaks that are still a bit not aligned with the UI mockups, though. I will directly point out the class names and the values. Hope it helps for you to find the places easier.

1. Remove the style `padding: 0 20px!important` in the div `#treasury-dashboard-view .ohm-card.ohm-chart-card .chart-card-header`.
2. In `#treasury-dashboard-view .hero-metrics__paper div.metric-container` ,  change the width value to `calc(100% / 3 - 15px)`, and change margin value to `20px 0 0 0`.
3. In `.mobile div.metric-container`, change the width value to `.mobile div.metric-container !important` and add margin value `10px 0 0 0 !important`.
4. Add another class for `#treasury-dashboard-view .hero-metrics` only applying to "mobile version" that the value of width could be `calc(100% - 10px)`, and add margin-left and margin-right both 5px.
6. In `.MuiToggleButton-root.Mui-selected`, change the background color to `white`, and border-radius to `0.3rem`.
Google Chrome_2022-05-25 14-57-06@2x
7. If it's possible to remove the shadow of the slide? It looks a little distracting in the dashboard but idk if it's generated by js. If there's a way to hide it, please do so.
Google Chrome_2022-05-25 15-15-15@2x

**Comment by abtheo** [comment]
@Appppo great, I appreciate the detailed feedback! Also feel free to make changes yourself - I'm good with data but front-end is definitely not my strong point 😂

I'll get to work now on your comments. One weird thing though, I've never seen that shadow on the slider 🤔
image

**Pull request merged**
